spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AilsaMa/mj-config.git
          search-paths: /**
          default-label: master
          username: ailsama
          password: Majun1990

